include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ToolboxSettingsModule
ToolboxSettingsModule_FILES = ToolboxSettingsModule.xm
ToolboxSettingsModule_LIBRARIES = ToolboxHelper
ToolboxSettingsModule_INSTALL_PATH = /Library/Toolbox

include $(THEOS_MAKE_PATH)/library.mk